[package]
name = "robots"
version = "0.1.0"
authors = ["Sarah Middleton <middleton.sarahlouise@gmail.com>"]

[dependencies]
piston_window = "0.64.0"
piston2d-sprite = "0.35.0"
find_folder = "0.3.0"
piston-ai_behavior = "0.19.0"